# Form implementation generated from reading ui file 'lay.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1082, 899)
        Dialog.setMinimumSize(QtCore.QSize(0, 899))
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(40, 40, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelResponse = QtWidgets.QLabel(parent=Dialog)
        self.labelResponse.setGeometry(QtCore.QRect(100, 140, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelResponse.setFont(font)
        self.labelResponse.setText("")
        self.labelResponse.setObjectName("labelResponse")
        self.lineEditName = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditName.setGeometry(QtCore.QRect(210, 40, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEditName.setFont(font)
        self.lineEditName.setObjectName("lineEditName")
        self.buttonClickMe = QtWidgets.QPushButton(parent=Dialog)
        self.buttonClickMe.setGeometry(QtCore.QRect(380, 220, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.buttonClickMe.setFont(font)
        self.buttonClickMe.setObjectName("buttonClickMe")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter your name"))
        self.buttonClickMe.setText(_translate("Dialog", "Submit"))
